[package]
name = "setup-configuration-sample"
version = "0.1.0"
authors = ["Alexander Ovchinnikov <8490695+Alovchin91@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
com = "0.4"
